### ISSUE TITLE
 Could not query proxy dbus: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.280 was not provided by any .service files

### ISSUE THREAD

**Issue by janbrummer** [janbrummer/libproxy2#107]
@DimStar77 @mcatanzaro 

We have implemented a inactivity timeout for the D-Bus service as requested by Michael in https://github.com/libproxy/libproxy/pull/157#pullrequestreview-561980205

This works more or less fine as the service will be shutdown after 1min. The downside is that we cannot rely on GDbusProxy as this does not handle state less services which will disappear/reapper between function calls: 
`
If the proxy is for a stateless D-Bus service, where the name owner may be started and stopped between calls, the GDBusProxy:g-name-owner tracking of GDBusProxy will cause the proxy to drop signal and property changes from the service after it has restarted for the first time. When interacting with a stateless D-Bus service, do not use GDBusProxy — use direct D-Bus method calls and signal connections.` 

https://docs.gtk.org/gio/class.DBusProxy.html

So we either have to rewrite the lib to use the low level d-bus functions or remove the application timeout. I would prefer to remove the timeout as otherwise all users of the d-bus service are most likely running in the same issue. Service is idling most of the time and memory consumption is low. Furthermore for every network request the service is restarted to check whether there is a proxy. Do we really need a timeout?

What do you think?

**Comment by DimStar77** [comment]
In this case I vote for 'no timeout' and keeping the elegant solution with GDbusProxy.

**Comment by janbrummer** [comment]
FTR: There is no G_IO_ERROR_CLOSED error raised, so i cannot just recreate the proxy.

**Comment by janbrummer** [comment]
Ok, this works... recreating a connection everytime query is called....

**Comment by janbrummer** [comment]
Will need to check the performance then
