### ISSUE TITLE
SONAME differs from libproxy 0.4.x / ABI break

### ISSUE THREAD

**Issue by DimStar77** [janbrummer/libproxy2#23]
Despite ensuring we keep the same ABi/API, the new libproxy library changes soname/soversion

Old library:

```
> readelf -a /usr/lib64/libproxy.so.1 | grep SONAME
 0x000000000000000e (SONAME)             Library soname: [libproxy.so.1]
```

New library:
```
> readelf -a /usr/lib64/libproxy-1.0.so | grep SONAME
 0x000000000000000e (SONAME)             Library soname: [libproxy-1.0.so]
```

This means the library cannot be used as a drop-in replacement and all consumers need to be rebuilt

**Comment by DimStar77** [comment]
also: the exported symbols are no longer versioned (e.g. openSUSE's existing wget package requires `libproxy.so.1(LIBPROXY_0.4.16)(64bit)`

**Comment by janbrummer** [comment]
PR welcome :P
