### ISSUE TITLE
tests not run according the meson options

### ISSUE THREAD

**Issue by DimStar77** [janbrummer/libproxy2#24]
Having tests enabled, but e.g. the soup downloader disabled, results in the test suite failing

`meson -Dtests=true -Ddownload-soup=false `

```

[    8s] ../src/tests/px-manager-test.c:25:10: fatal error: libsoup/soup.h: No such file or directory
[    8s]    25 | #include <libsoup/soup.h>
[    8s]       |          ^~~~~~~~~~~~~~~~
[    8s] compilation terminated.

```

**Comment by janbrummer** [comment]
The thing is that px-manager-test depends on soup to create a server for download pac files. So he only thing i can do here is to make this test depend on the existing of libsoup. Fine?

**Comment by DimStar77** [comment]
> The thing is that px-manager-test depends on soup to create a server for download pac files. So he only thing i can do here is to make this test depend on the existing of libsoup. Fine?

That makes sense. We should test the things that we can based on the picked options; things that are intentionally disabled result in a disabled test
