### ISSUE TITLE
D-Bus implementation

### ISSUE THREAD

**Issue by janbrummer** [janbrummer/libproxy2#42]
# libproxy - D-Bus

## Existing Requirement
libproxy should be implemented as a D-Bus Service on Linux, running in **USER SESSION**, so it is able to handle
user Desktop Environment configuration => Different settings for each user possible.

## Problem
- Autostarting services before User Session will fail, because autostarting D-Bus User Session requires X11 Session ID...
- Working around with calling D-Bus directly does not change anything, as the request cannot be fullfilled now!

## Solution 1
Move service to **SYSTEM SESSION** but this will loose all plugin code... proxy configuration must be implemented in NM/ConnMan then. Service will be run as a separate user (just like the current implementation in connman).

## Solution 2
Leave it as a **library**. Problem there is libsoup2 vs libsoup3 apps. Moving enitrely to curl possible...

## Solution 3
Leave it in **USER SESSION** and change every app using libproxy to delay calls...

**Comment by janbrummer** [comment]
@DimStar77  @mcatanzaro Any idea? Suggestions?

**Comment by janbrummer** [comment]
## Solution 4

Add core **SYSTEM SESSION** and allow a new **USER SESSION** to feed configuration into **SYSTEM SESSION** for given user..

**Comment by mcatanzaro** [comment]
You're making this too complicated! libproxy should certainly only use the session bus, not the system bus.

The libproxy library can first check if the libproxy service is available on the session bus. For NetworkManager, which runs outside any user session, that check will fail. Then the library can fall back to local operation. dlopen the PAC plugin so you only load libsoup if D-Bus is unavailable, that way programs can link to libproxy without linking to libsoup, and only programs that run outside the user session need to worry about avoiding libsoup 2 vs. libsoup 3.

This should work!

**Comment by janbrummer** [comment]
Haven't thought about this :) Always good to ask for feedback. What about sudo calls? I'd loved to see them picking up the right proxy as well. Wouldn't this be convenient?

**Comment by janbrummer** [comment]
Haven't thought about this :) Always good to ask for feedback.

I was able to tame it.  \o/

 What about sudo calls? I'd loved to see them picking up the right proxy as well. Wouldn't this be convenient?
