### ISSUE TITLE
potential build cycle with libcurl

### ISSUE THREAD

**Issue by DimStar77** [janbrummer/libproxy2#57]
The current build setup will bring us to a cycle when plans work out:

* To build libproxy, we require libcurl (unconditionally)
* the goal is to have luibcurl build against libproxy

We should try to produce the 'client library' with minimal build deps (at least on OSes where we have client/daemon setup)

**Comment by mcatanzaro** [comment]
Could have libcurl itself ship the wpad support as a libproxy extension?

Or alternatively, if need be: could go back to soup if need be and have libsoup do that.

**Comment by mcatanzaro** [comment]
I dunno, build cycles are awkward, but avoiding them is awkward too....

**Comment by janbrummer** [comment]
We talked about it today and we will add an option to build libproxy without curl (so no pac support). Then curl can be build and then libproxy curl buildin module will be build.
